/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Set;

/**
 *
 * @author sence
 */
public class home extends Main {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    public  void initComponents() {
        System.out.println("home -> initComponents");
        지역별관광지버튼 = new JButton();
        지역별날씨정보버튼 = new JButton();
        관광치추천버튼 = new JButton();
        jLabel1 = new JLabel();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        지역별관광지버튼.setBackground(new Color(158, 141, 186));
        지역별관광지버튼.setFont(new Font("맑은 고딕", 0, 36)); // NOI18N
        지역별관광지버튼.setForeground(new Color(255, 255, 255));
        지역별관광지버튼.setText("지역별 관광지");

        지역별날씨정보버튼.setBackground(new Color(158, 141, 186));
        지역별날씨정보버튼.setFont(new Font("맑은 고딕", 0, 36)); // NOI18N
        지역별날씨정보버튼.setForeground(new Color(255, 255, 255));
        지역별날씨정보버튼.setText("지역별 날씨정보");

        관광치추천버튼.setBackground(new Color(158, 141, 186));
        관광치추천버튼.setFont(new Font("맑은 고딕", 0, 36)); // NOI18N
        관광치추천버튼.setForeground(new Color(255, 255, 255));
        관광치추천버튼.setText("관광지추천");

        jLabel1.setIcon(new ImageIcon(getClass().getResource("/images/홈.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(421, 421, 421)
                .addComponent(지역별관광지버튼, GroupLayout.PREFERRED_SIZE, 330, GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(지역별날씨정보버튼, GroupLayout.PREFERRED_SIZE, 330, GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(관광치추천버튼, GroupLayout.PREFERRED_SIZE, 327, GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 1700, GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(지역별관광지버튼, GroupLayout.PREFERRED_SIZE, 137, GroupLayout.PREFERRED_SIZE)
            .addComponent(지역별날씨정보버튼, GroupLayout.PREFERRED_SIZE, 137, GroupLayout.PREFERRED_SIZE)
            .addComponent(관광치추천버튼, GroupLayout.PREFERRED_SIZE, 137, GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel1)
        );
        ActionListener localweatherPanel = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                setVisible(false);

                lw.setVisible(true);
                System.out.println("홈에서지역날씨");
            }
        };
        지역별날씨정보버튼.addActionListener(localweatherPanel);

        ActionListener localattractionPanel = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                setVisible(false);

                la.setVisible(true);
                System.out.println("홈에서지역관광지추천");
            }
        };
        지역별관광지버튼.addActionListener(localattractionPanel);

        ActionListener recommendattractionPanel = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                setVisible(false);

                ra.setRamdomspot();
                ra.setVisible(true);
                System.out.println("홈에서관광지추천");
            }
        };
        관광치추천버튼.addActionListener(recommendattractionPanel);
        pack();


    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify


    private JLabel jLabel1;
    private JButton 관광치추천버튼;
    private JButton 지역별관광지버튼;
    private JButton 지역별날씨정보버튼;
    // End of variables declaration                   
}
